name: excercise
description: simple command line dart application to learn dart
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-9.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
